### ISSUE TITLE
Battery drain on EV?

### ISSUE THREAD

**Issue by tuxedo0801** [Hacksore/bluelinky#184] opened 2021-12-22 15:24 UTC
Hi there,

just wondering whether regular queries (every 5mins?) will drain my EVs 12V battery?!
Does anyone know?

**Comment by PierreLevres** [comment] 2021-12-22 16:16
Yes it will when refresh is forced

**Comment by tuxedo0801** [comment] 2021-12-22 16:58
Great. Then you should write this in big upper case letters into the readme, or?

**Comment by Hacksore** [comment] 2021-12-22 22:26
The default value for `refresh` is `false`

https://github.com/Hacksore/bluelinky/blob/develop/src/constants.ts#L26

**Comment by tuxedo0801** [comment] 2021-12-23 08:23
And how this will stop people from doing regular refresh by an endless loop? And how will they know that regular refreshes drain their battery?

This is a serious issue. Got a new car, used the library via nodered and queried status every 5min, because I thought it works like Renault: always ask the Cloud, not the car itself.
Result: struggled two days with broken battery and went to the garage without any finding. But finally I remembered my API queries ... And now I'm here.

I'm pretty sure that it makes a lot of sense to tell the people via Readme file that making regular queries can drain their car battery until the car will reject any interaction, even unlocking by remote key.

**Comment by Hacksore** [comment] 2021-12-23 14:27
If you are doing endless refresh queries what else would you expect?

I understand that a message in the readme would be beneficial, submit a PR.

**Comment by PierreLevres** [comment] 2021-12-23 17:48
> If you are doing endless refresh queries what else would you expect?
> 
> I understand that a message in the readme would be beneficial, submit a PR.

I did...

**Comment by tuxedo0801** [comment] 2021-12-23 19:55
> If you are doing endless refresh queries what else would you expect?

How do you think people know that every query is sent to their car? I expected to query the last status the car has sent to the cloud from the cloud. I never expected that every query is sent to the car. I expected some kind of indirection. But this is more like a direct connection, with the cloud as a proxy.
That's why I find it so confusing. And that's why I expect to get warned by readme

**Comment by PierreLevres** [comment] 2021-12-23 20:05
You might wanna try pressing the refresh button in you app every 5 minutes. And when your battery is drained send a  formal complaint to Kia/Hyundai that the app didn't give you any warning? I wonder if they would change the readme file.

And instead of being irritated that the readme isn't up to your standards you could also be grateful that a group of volunteers is spending their precious spare time building something for the community.
You could also try to contribute by submitting a PR for the things you like to be changed.

**Comment by Hacksore** [comment] 2021-12-27 16:11
Merged #185 which should give a warning in the readme. Feel free to continue the discussion but I'm closing this issue.

**Closed by Hacksore** 2021-12-27 16:11 UTC

**Comment by cr0ste** [comment] 2024-02-09 15:43
Despite of the adapted ReadMe, there seems to be still some confusion about it, as it's not very clear to non-insiders what "refresh" means. 

What I understand from this discussion is that the car battery is only drained when using "refresh: true".  
In several communities poeple are discussing about battery drain of bluelinky and interprete the new ReadMe as "You should not call bluelinky too often" (not knowing about refresh true/false toggle). 

Can one of you please state if my assumption is right that no drain should happen with refresh=false? 
If so, I would probably create another PR to make it more clear ;-)

**Comment by PierreLevres** [comment] 2024-02-10 04:08
Your assumption is right. Op 9 feb 2024 om 16:43 heeft cr0ste ***@***.***> het volgende geschreven:﻿
Despite of the adapted ReadMe, there seems to be still some confusion about it, as it's not very clear to non-insiders what "refresh" means.
What I understand from this discussion is that the car battery is only drained when using "refresh: true".
In several communities poeple are discussing about battery drain of bluelinky and interprete the new ReadMe as "You should not call bluelinky too often" (not knowing about refresh true/false toggle).
Can one of you please state if my assumption is right that no drain should happen with refresh=false?
If so, I would probably create another PR to make it more clear ;-)

**Comment by cr0ste** [comment] 2024-04-20 09:23
@Hacksore @PierreLevres 
Unfortunately it turned out that the assumption is not right (no blame to your great work though!). 

We have our Kia since 1.5 years now and since 1 year we have a lot of full outages of our 12 V battery. 
Multiple Kia service partners did not find a root cause yet. But I did, since I finally bought a battery guard / monitor. 
On each request to blulinky, of course with refresh=false, there is a short drop of voltage, which clearly shows that something happens in the car. I'm doing a request every hour. After 1 to 2 days the battery is empty. (Battery is probably damaged already and a fresh one would last longer). 

So now the question is if this is somehow solvable. I think that my usage is correct. And I also assume its not a general problem, as you guys would be aware of it then. 
Could you imagine that it is car model specific whether tje blulinky request to the server is doing a refresh or not? I have a Niro EV SG2 from end of 2022.
