### ISSUE TITLE
2nd car with nod red

### ISSUE THREAD

**Issue by olivierjag2** [Hacksore/bluelinky#187] opened 2021-12-27 12:38 UTC
**Describe the bug**
When I add the second car in node red, my first car stop working

1rd car Kia Canada
2nd car Hyundai Canada

 - Region: CA
 - Brand: kia, hyundai

**Comment by Hacksore** [comment] 2021-12-27 16:25
@olivierjag2 Did you configure two bluelinky configs for each vehicle and use them accordingly in each node?

![image](https://user-images.githubusercontent.com/996134/147489879-89aa403d-6385-4594-91e5-9a2d1ea25002.png)

**Comment by justinoreilly** [comment] 2021-12-27 16:44
I also have the same issue. I have experienced similar behavior for about 2 months just haven't got around to submitting a PR until I saw this one flash through. I am in the US region though and each of my vehicles has a separate BlueLink account.
<img width="693" alt="Screen Shot 2021-12-27 at 11 41 48 AM" src="https://user-images.githubusercontent.com/7625409/147491172-46c2e17b-2a6e-40ab-83a5-a3d5cdf71cdc.png">
On the offending configuration I get the following error:
`"Error: Vehicle not found: REDACTEDVIN!"`

**Comment by Hacksore** [comment] 2021-12-27 17:01
@justinoreilly is it possible the [case bug](https://github.com/Hacksore/bluelinky/commit/c707b80ed3a92be5a27bbf5fefa6be4edbb48a13#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80R114) was related here?

Depending on how the Hyundai server was storing the VIN it could have been trying to, for example, compare the following which would fail.

`VINABCD1234567890` == `vinabcd1234567890`

**Comment by justinoreilly** [comment] 2021-12-27 17:12
@Hacksore I was able to confirm the case issue with the working vehicle. Setting the VIN to lowercase caused a fail. Upon changing it back to uppercase it worked. 

I attempted to do the same with the vehicle that wasn't working and it produces the same error regardless of uppercase or lowercase VIN. 

Also not sure if this is related but I am unable to rename the bluelinky config node. If I attempt to change it, It reverts back to Bluelinky
<img width="465" alt="Screen Shot 2021-12-27 at 12 10 53 PM" src="https://user-images.githubusercontent.com/7625409/147493170-a8e48d76-0335-4e57-9f6a-82e1dfec8556.png">

**Comment by Hacksore** [comment] 2021-12-27 17:35
Yeah looks like it's kind of related - we need to refactor a bit to support multiple vehicles in the node-red addon.

Right now there is only a single instance of bluelinky globally which is the root cause of the problem.

Closing in favor of the ticket downstream https://github.com/SondreNjaastad/node-red-contrib-bluelinky/issues/62

**Closed by Hacksore** 2021-12-27 17:35 UTC
