### ISSUE TITLE
Engine not starting using homekit

### ISSUE THREAD

**Issue by james5294** [Hacksore/bluelinky#180] opened 2021-11-08 04:05 UTC
Describe the bug
The engine of my Hyundai does not successfully start. (via homebridge bluelink plugin which uses BlueLinky)

Useful info(please complete the following information):

OS: Homebridge (Linux)
Version: BlueLinky 7.6.2
Region: US
Vehicle:  2021 Palisade

Additional context
When trying to start the engine through Apple HomeKit the command gets sent however the command doesn't seem to get executed. To elaborate, the command to start the ignition IS in fact going through however it seems like the command that's being sent is incorrect as the BlueLink app DOES in fact register that there is a command being sent however the command seems to have no action. When I try to toggle the Ignition from HomeKit if i go right to the BlueLink app and trying to execute any remote action it says "We are currently processing an earlier inquiry for your vehicle please wait 90 seconds..." So it received the ignition start command its just failing to execute.

The developer of the Homebridge plugin thinks its an issue with BlueLinky. Please let me know if theres anything i can try to help further debug this issue.

**Comment by james5294** [comment] 2021-11-30 14:09
nothing?

**Comment by Hacksore** [comment] 2021-11-30 16:19
@james5294 have you tried to reproduce in bluelinky without using HomeKit?

Sharing the debug logs from that could help move this ticket in a forward direction.

**Comment by james5294** [comment] 2021-12-15 03:46
@Hacksore not shure how to use it other than this? this is my only use. any ideas?

**Comment by Hacksore** [comment] 2021-12-15 04:03
@james5294 you'd need to clone this repo and follow this https://github.com/Hacksore/bluelinky#debug-locally

**Comment by Hacksore** [comment] 2022-01-11 15:22
I'd say before we visit anything here we have [homebridge-hyundai-bluelink](https://github.com/athal7/homebridge-hyundai-bluelink) updated to use bluelinky `v7.6.2`.

However, it looks like @athal7 is in the same boat as I am, we no longer own Hyundai vehicles 😅. 

@james5294 I'll close this issue for now but if you can get this tested on the latest bluelinky please raise a new issue.

**Closed by Hacksore** 2022-01-11 15:22 UTC
