### ISSUE TITLE
Enable Kia cars in Europe

### ISSUE THREAD

**Issue by plips-nl** [Hacksore/bluelinky#41] opened 2020-05-18 21:03 UTC
This wonderful project is aimed ad Hyundai cars. Effectively Hyundai and Kia use the same apps, websites, interfaces.

For Europe, replacing Hyundai to Kia in EU_BASE_URL constant (in lib/constants.ts)  would open up this project to Kia drivers too. 

export const EU_BASE_URL = 'https://prd.eu-ccapi.kia.com:8080';

Might it be possible to somehow implement that? Choosing a brand in the parameters and change base_url accordingly?

**Comment by Hacksore** [comment] 2020-05-18 21:20
@plips-nl Can you confirm that this works? In the USA we have only one car that works for UVO (2020 Telluride) AFAIK.

I'm not 100% confident we can just change the base URL it would just work but feel free to prove me wrong.

If we get some traction around UVO maybe we can look to start supporting it in the lib but as of now, we've only focused on Hyundai/Genesis.

**Comment by SondreNjaastad** [comment] 2020-05-18 21:24
@plips-nl, would you be interested to join out Discord Channel to discuss this further?

**Comment by plips-nl** [comment] 2020-05-18 21:25
Not 100% confident. I am not a programmer myself. I could try to fork the project myself, change base url and test it somehow. 
I am more into python then typescript so will have to figure some things out. 

Groet,
Peter Lips

**Comment by plips-nl** [comment] 2020-05-18 21:26
I would yes of course. 


Groet,
Peter Lips

**Comment by SondreNjaastad** [comment] 2020-05-19 04:09
@plips-nl link is in the readme, Green chat icon 😊

**Comment by Amxt** [comment] 2020-05-22 12:21
The KIA app seems to be identical to the Hyundai app for Europe (even at the code level). The difference is the base url which was already mentioned (https://prd.eu-ccapi.kia.com:8080) but also the client_id and the basic authentication token for the /token endpoint (These I've confirmed). The GCM Sender Id may also be different. If someone is able to get these then this API should in theory work perfectly with KIA.

**Comment by raleeSheffield** [comment] 2020-06-27 15:03
I'm definitely interested in applying it to Kia - wanting to get my OpenEvse charger working better with e-Niro.

If this is done can there be an option in the Node Red implementation to select Kia/Hyundai?

I'm a bit of a programmer, but not much(!), mainly I never can work out how all the different bits fit together, but I write code once I'm in a particular environment (not sure that makes sense but hey...)

**Comment by plips-nl** [comment] 2020-07-03 13:59
well, I forked the master branch, changed all constants of hyundai to the kia equivalent and am happy to test and experiment, but as a total newbie on ts programming and coding, how do i get from a set up ts files (locally cloned) to a set of js files running in nodejs ? (nodejs is running, node-red on port 1880 is responding, npm is installed, tsc is installed)...

**Comment by Pyromancer579** [comment] 2020-07-07 16:43
I too would like to be able to read my Kia E-Niro batterys state of charge, like raleeSheffield, to make my Zappi smart EV charger even more 'intelligent'.

I have only just started coding, having not done it in anger for more than 30 years (it was called programming back then), I'm learning Python, but early days yet (literally just a few days), so I'm not in a position to develop the base modules.

But I'd encourage those that can do this type of impressive work to get a full Python API working for Kia Uvo, so I and others can play with it at the top level to do the magical things we want.

Thanks for all the work put in so far and I'm really looking forward to seeing how this project progresses.

**Comment by Hacksore** [comment] 2020-07-07 16:59
I'm thinking about making Kia support out of scope for the project as it's adding more complexity. If we want to, in the end, create a super lib that can wrap all of them together we can do that (think [smartcar ](https://smartcar.com/) but free and opensource). 

So, in theory, you'd have bluelinky that can encapsulate Hyundai to the best ability. Then you'd have "kialink" to better isolate changes specific to the Kia UVO service. When it comes down to it even though they share similarities I think it's better to keep them isolated.

With that said, there is another project that is being built in python that supports Kia created by @wcomartin.

At this time I believe it might only support Canada but I'm sure those interesting can make it work for other regions too.

https://github.com/wcomartin/kiauvo

@SondreNjaastad feel free to add your opinions here as well since this discussion is good for the project.

**Comment by SondreNjaastad** [comment] 2020-07-07 22:18
I agree with @Hacksore. at the moment the APIs are much the same, but there is no guarantee for the future, and grouping it based on services would make a lot of sense. Building such a big service will require a lot of dedicated people for each platform, so the best initiate someone could do to get started would be to start connecting and speaking to anyone interested.

**Comment by MaxvandeLaar** [comment] 2020-07-08 05:44
@SondreNjaastad I am definitely interested in something like that. My Kia E-Niro will arrive late October so at that point I want to create an Homey app (JS). So if the Kia alternative npm lib does not yet exist I will most likely create it. 

If more people are interested in creating a open source free smartcar wrapper, count me in 😉

**Comment by Hacksore** [comment] 2020-07-13 02:38
Closing the issue as I believe the best option is to make a stand-alone project.

**Closed by Hacksore** 2020-07-13 02:38 UTC
Labels: discussion
